services:
  # Redis avec module JSON pour le Task Manager
  redis:
    image: redis/redis-stack:latest
    container_name: ${PROJECT_NAME:-myproject}-task-redis
    ports:
      - "6380:6379" # Redis sur port 6380 (externe)
      - "8001:8001" # RedisInsight sur port 8001 (externe)
    volumes:
      - task-redis-data:/data
    environment:
      - REDIS_ARGS=--save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - local_default

  # Task Manager Application
  task-manager:
    build:
      context: ../
      dockerfile: Task_manager/task-manager.Dockerfile
      args:
        - PROJECT_NAME=${PROJECT_NAME:-MyProject}
    container_name: ${PROJECT_NAME:-myproject}-task-manager
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - PROJECT_NAME=${PROJECT_NAME:-MyProject}
      - REDIS_HOST=${PROJECT_NAME:-myproject}-task-redis
      - REDIS_PORT=6379 # Port interne du conteneur Redis
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - local_default

  # Interface Web RedisInsight (inclus dans redis-stack)
  # Accessible via http://localhost:8001

volumes:
  task-redis-data:
    driver: local
    name: ${PROJECT_NAME:-myproject}-task-redis-data

networks:
  local_default:
    external: true
