services:
  # Redis avec module JSON pour le Task Manager
  redis:
    image: redis/redis-stack:latest
    container_name: agroflow-task-redis
    ports:
      - "6380:6379" # Redis sur port 6380 (externe)
      - "8002:8001" # RedisInsight sur port 8002 (externe)
    volumes:
      - agroflow-task-redis-data:/data
    environment:
      - REDIS_ARGS=--save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - local_default

  # Task Manager Application
  task-manager:
    build:
      context: ../
      dockerfile: Task_manager/task-manager.Dockerfile
    container_name: agroflow-task-manager
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - REDIS_HOST=agroflow-task-redis
      - REDIS_PORT=6379 # Port interne du conteneur Redis
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - local_default

  # Interface Web RedisInsight (inclus dans redis-stack)
  # Accessible via http://localhost:8002

volumes:
  agroflow-task-redis-data:
    driver: local

networks:
  local_default:
    external: true
